# Generated by Django 4.1.7 on 2023-03-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-date_added',)},
        ),
    ]
