# Generated by Django 4.1.7 on 2023-03-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='day',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
