# Generated by Django 4.1.7 on 2023-03-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_day_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('date_added',)},
        ),
    ]
