# Generated by Django 4.1.7 on 2023-03-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_alter_recipe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
