# Generated by Django 4.1.7 on 2023-03-21 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
    ]
