# Generated by Django 4.1.7 on 2023-03-21 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_preferences_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cook_minutes', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(480), django.core.validators.MinValueValidator(10)])),
                ('max_cook_minutes', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(480), django.core.validators.MinValueValidator(10)])),
                ('cuisines', models.ManyToManyField(related_name='meal_settings', to='recipe.category')),
                ('preferences', models.ManyToManyField(related_name='meal_settings', to='recipe.preferences')),
            ],
        ),
    ]
