# Generated by Django 4.1.7 on 2023-03-22 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_mealsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(0)]),
        ),
    ]
