# Generated by Django 4.1.7 on 2023-03-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_alter_preferences_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preferences',
            field=models.ManyToManyField(related_name='recipe', to='recipe.preferences'),
        ),
    ]
