# Generated by Django 4.1.7 on 2023-04-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0021_recipe_image_external_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='title',
        ),
    ]
